verbs:
  - name: Սիրել
    type: accusative # հայցական
    third_person_present: կը սիրէ
  - name: Տեղեկացնել
    type: dative # տրական
    third_person_present: կը տեղեկացնէ
  - name: Տալ
    type: dative
    third_person_present: կու տայ
  - name: Ղրկել
    type: dative
    third_person_present: կը ղրկէ
  - name: Հրաւիրել
    type: accusative
    third_person_present: կը հրաւիրէ
  - name: Սորվեցնել
    type: dative
    third_person_present: կը սորվեցնէ
  - name: Ճանչնալ # added on 2025-11-30
    type: accusative
    third_person_present: կը ճանչնայ
  - name: Սպասել # added on 2025-11-30
    type: dative
    third_person_present: կը սպասէ
  - name: Ոչնչացնել # added on 2025-11-30
    type: accusative
    third_person_present: կ՚ոչնչացնէ
  - name: Ամբաստանել # added on 2025-12-02
    type: accusative
    third_person_present: կ՚ամբաստանէ
  - name: Յիշել # added on 2025-12-02
    type: accusative
    third_person_present: կը յիշէ
  - name: Հետաքրքրել # added on 2025-12-02
    type: accusative
    third_person_present: կը հետաքրքրէ
  - name: Տեղեակ պահել # added on 2025-12-08
    type: accusative
    third_person_present: տեղեակ կը պահէ
  - name: Թուիլ # added on 2025-12-14
    type: dative
    third_person_present: կը թուի
  - name: Գտնել # added on 2025-12-14
    type: accusative
    third_person_present: կը գտնէ
# ...
