verbs:
  - name: Սիրել
    type: accusative # հայցական
    first_person_present: կը սիրեմ
  - name: Տեղեկացնել
    type: dative # տրական
    first_person_present: կը տեղեկացնեմ
  - name: Տալ
    type: dative
    first_person_present: կու տամ
  - name: Ղրկել
    type: dative
    first_person_present: կը ղրկեմ
  - name: Հրաւիրել
    type: accusative
    first_person_present: կը հրաւիրեմ
  - name: Սորվեցնել
    type: dative
    first_person_present: կը սորվեցնեմ
  - name: Ճանչնալ # added on 2025-11-30
    type: accusative
    first_person_present: կը ճանչնամ
  - name: Սպասել # added on 2025-11-30
    type: dative
    first_person_present: կը սպասեմ
  - name: Ոչնչացնել # added on 2025-11-30
    type: accusative
    first_person_present: կը ոչնչացնեմ
  - name: Ամբաստանել # added on 2025-12-02
    type: accusative
    first_person_present: կ'ամբաստանեմ
  - name: Յիշել # added on 2025-12-02
    type: accusative
    first_person_present: կը յիշեմ
  - name: Հետաքրքրել # added on 2025-12-02
    type: accusative
    first_person_present: կը հետաքրքրեմ
  - name: Տեղեակ պահել # added on 2025-12-02
    type: accusative
    first_person_present: տեղեակ կը պահեմ
# ...
