verbs:
  - name: Սիրել
    type: accusative # հայցական
    third_person_present: կը սիրէ
  - name: Տեղեկացնել
    type: dative # տրական
    third_person_present: կը տեղեկացնէ
  - name: Տալ
    type: dative
    third_person_present: կու տայ
  - name: Ղրկել
    type: dative
    third_person_present: կը ղրկէ
  - name: Հրաւիրել
    type: accusative
    third_person_present: կը հրաւիրէ
  - name: Սորվեցնել
    type: dative
    third_person_present: կը սորվեցնէ
  - name: Ճանչնալ # added on 2025-11-30
    type: accusative
    third_person_present: կը ճանչնայ
  - name: Սպասել # added on 2025-11-30
    type: dative
    third_person_present: կը սպասէ
  - name: Ոչնչացնել # added on 2025-11-30
    type: accusative
    third_person_present: կ՚ոչնչացնէ
  - name: Ամբաստանել # added on 2025-12-02
    type: accusative
    third_person_present: կ՚ամբաստանէ
  - name: Յիշել # added on 2025-12-02
    type: accusative
    third_person_present: կը յիշէ
  - name: Հետաքրքրել # added on 2025-12-02
    type: accusative
    third_person_present: կը հետաքրքրէ
  - name: Տեղեակ պահել # added on 2025-12-08
    type: accusative
    third_person_present: տեղեակ կը պահէ
  - name: Թուիլ # added on 2025-12-14
    type: dative
    third_person_present: կը թուի
  - name: Գտնել # added on 2025-12-14
    type: accusative
    third_person_present: կը գտնէ
  - name: Ուրախացնել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ուրախացնէ
  - name: Մտահոգել # added on 2025-12-24
    type: accusative
    third_person_present: կը մտահոգէ
  - name: Ձգել # added on 2025-12-24
    type: accusative
    third_person_present: կը ձգէ
  - name: Ազատել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ազատէ
  - name: Ազգայնացնել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ազգայնացնէ
  - name: Ածիլել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ածիլէ
  - name: Ակնարկել # added on 2025-12-24
    type: dative
    third_person_present: կ՚ակնարկէ
  - name: Ակօսել # added on 2025-12-24
    type: dative
    third_person_present: կ՚ակօսէ
  - name: Աղաչել # added on 2025-12-24
    type: dative
    third_person_present: կ՚աղաչէ
  - name: Աղալ # added on 2025-12-24
    type: accusative
    third_person_present: կ՚աղայ
  - name: Ամուսնացնել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ամուսնացնէ
  - name: Ամչցնել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ամչցնէ
  - name: Այրել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚այրէ
  - name: Այցելել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚այցելէ
  - name: Անարգել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚անարգէ
  - name: Անիծել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚անիծէ
  - name: Ապշեցնել # added on 2025-12-24
    type: accusative
    third_person_present: կ՚ապշեցնէ
# ...
